export const items = [
  {
    id: "banner_01",
    isBanner: true,
    colSpan: 2,
    rowSpan: 2,
    video: {
      src: "./videos/cha.mp4",
      width: 746,
      height: 1078,
    },
  },
  {
    id: "product_01",
    thumbnail: "./images/thumbnail_01.jpg",
    thumbnails: [
      "./images/thumbnail_01_01.jpg",
      "./images/thumbnail_01_02.jpg",
      "./images/thumbnail_01_03.jpg",
    ],
    label: "New Arrival",
    hearted: false,
    title: "M'S GORETEX HIKER JACKET",
    price: "419,000원",
    tags: ["산행용", "레귤러핏"],
  },
  {
    id: "product_02",
    thumbnail: "./images/thumbnail_02.jpg",
    hearted: false,
    title: "M'S LEWES T VEST",
    price: "139,000원",
    tags: ["여행용", "간절기방한용", "레귤러핏"],
  },
  {
    id: "product_03",
    href: "../pdp/",
    thumbnail: "./images/thumbnail_03.jpg",
    hearted: false,
    title: "M'S GORETEX HIKER JACKET",
    price: "419,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["산행용", "레귤러핏"],
  },
  {
    id: "product_04",
    thumbnail: "./images/thumbnail_04.jpg",
    hearted: false,
    title: "M'S MARION ON BALL JACKET",
    price: "160,00원",
    discount: "20%",
    originalPrice: "200,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["방한용", "루즈핏"],
  },
  {
    id: "product_05",
    thumbnail: "./images/thumbnail_05.jpg",
    hearted: false,
    label: "New Arrival",
    title: "M'S MOUNTAIN PEAK JACKET",
    price: "249,000원",
    tags: ["아웃도어활동용", "레귤러핏"],
  },
  {
    id: "product_06",
    thumbnail: "./images/thumbnail_06.jpg",
    hearted: false,
    title: "M'S KANTEGA GTX JACKET SE",
    price: "679,000원",
    tags: ["고산원정용용", "베이스캠프용"],
  },
  {
    id: "product_07",
    thumbnail: "./images/thumbnail_07.jpg",
    hearted: false,
    label: "White Label",
    title: "HI MOUNTAIN JACKET",
    price: "219,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["캠핑용", "레귤러핏"],
  },
  {
    id: "product_08",
    thumbnail: "./images/thumbnail_08.jpg",
    hearted: false,
    title: "RESTON JACKET",
    price: "98,000원",
    discount: "30%",
    originalPrice: "140,000원",
    tags: ["여행용", "루즈핏"],
  },
  {
    id: "product_09",
    thumbnail: "./images/thumbnail_09.jpg",
    hearted: false,
    label: "White Label",
    title: "SLOPE 3L JACKET",
    price: "278,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["여행용", "오버핏"],
  },
  {
    id: "banner_02",
    isBanner: true,
    colSpan: 2,
    image: {
      src: "./images/banner_row_1_col_2.png",
      width: 746,
      height: 534,
    },
  },
  {
    id: "product_10",
    thumbnail: "./images/thumbnail_10.jpg",
    hearted: false,
    title: "ACTION FREE RDS DOWN COAT",
    price: "358,000원",
    tags: ["방한용", "레귤러핏"],
  },
  {
    id: "product_11",
    thumbnail: "./images/thumbnail_11.jpg",
    hearted: false,
    label: "New Arrival",
    title: "PO TEAMKOREA ICE RUN JACKET/R",
    price: "161,100원",
    discount: "10%",
    originalPrice: "179,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["양말증정"],
  },
  {
    id: "product_12",
    thumbnail: "./images/thumbnail_12.jpg",
    hearted: false,
    label: "New Arrival",
    title: "PO TEAMKOREA RESTON JACKET/R",
    price: "162,000원",
    discount: "10%",
    originalPrice: "180,000원",
    tags: ["양말증정"],
  },
  {
    id: "product_13",
    thumbnail: "./images/thumbnail_13.jpg",
    hearted: false,
    title: "SLOPE 3L JACKET",
    price: "278,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["여행용", "오버핏"],
  },
  {
    id: "product_14",
    thumbnail: "./images/thumbnail_14.jpg",
    hearted: false,
    title: "M'S 1996 ECO NUPTSE JACKET",
    price: "399,000원",
    tags: ["아웃도어활동용", "방한용", "레귤러핏"],
  },
  {
    id: "product_15",
    thumbnail: "./images/thumbnail_15.jpg",
    hearted: false,
    title: "SLOPE 3L JACKET",
    price: "278,000원",
    tags: ["여행용", "오버핏"],
  },
  {
    id: "banner_03",
    isBanner: true,
    colSpan: 2,
    rowSpan: 2,
    image: {
      src: "./images/banner_row_2_col_2.png",
      width: 746,
      height: 1078,
    },
  },
  {
    id: "product_16",
    thumbnail: "./images/thumbnail_16.jpg",
    hearted: false,
    title: "COMFY FLEECE ANORAK",
    price: "438,000원",
    tags: ["여행용", "레귤러핏"],
  },
  {
    id: "product_17",
    thumbnail: "./images/thumbnail_17.jpg",
    hearted: false,
    title: "M'S LEWES T JACKET",
    price: "169,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["여행용", "간절기방한용", "레귤러핏"],
  },
  {
    id: "product_18",
    thumbnail: "./images/thumbnail_18.jpg",
    hearted: false,
    label: "White Label",
    title: "NEO VAIDEN JACKET",
    price: "196,200원",
    tags: ["여행용", "레귤러핏"],
  },
  {
    id: "product_19",
    thumbnail: "./images/thumbnail_19.jpg",
    hearted: false,
    title: "M'S EXPLORING MESH VEST",
    price: "96,000원",
    discount: "20%",
    originalPrice: "120,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["캠핑용", "레귤러핏"],
  },
  {
    id: "product_20",
    thumbnail: "./images/thumbnail_20.jpg",
    hearted: false,
    label: "New Arrival",
    title: "FELIX GORE-TEX JACKET",
    price: "503,200원",
    tags: ["전문등산용", "레귤러핏"],
  },
  {
    id: "product_21",
    thumbnail: "./images/thumbnail_21.jpg",
    hearted: false,
    label: "New Arrival",
    title: "M'S LEWES T VEST",
    price: "139,000원",
    tags: ["여행용", "간절기방한용", "레귤러핏"],
  },
  {
    id: "product_22",
    thumbnail: "./images/thumbnail_22.jpg",
    hearted: false,
    title: "M'S GO MOUNTAIN JACKET",
    price: "179,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["산행용", "레귤러핏"],
  },
  {
    id: "product_23",
    thumbnail: "./images/thumbnail_23.jpg",
    hearted: false,
    title: "FELIX GORE-TEX JACKET",
    price: "496,000원",
    discount: "20%",
    originalPrice: "620,000원",
    tags: ["전문등산용", "레귤러핏"],
  },
  {
    id: "product_24",
    thumbnail: "./images/thumbnail_24.jpg",
    hearted: false,
    label: "White Label",
    title: "NOVELTY NUPTSE RDS DOWN JACKET",
    price: "398,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["레귤러핏"],
  },
  {
    id: "product_25",
    thumbnail: "./images/thumbnail_25.jpg",
    hearted: false,
    title: "NOVELTY NUPTSE RDS DOWN VEST",
    price: "268,000원",
    tags: ["여행용", "레귤러핏"],
  },
  {
    id: "product_26",
    thumbnail: "./images/thumbnail_26.jpg",
    hearted: false,
    title: "FELIX GORE-TEX JACKET",
    price: "496,000원",
    discount: "20%",
    originalPrice: "620,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["전문등산용", "레귤러핏"],
  },
  {
    id: "product_27",
    thumbnail: "./images/thumbnail_27.jpg",
    hearted: false,
    label: "White Label",
    title: "NEO VAIDEN JACKET",
    price: "196,200원",
    tags: ["여행용", "레귤러핏"],
  },
  {
    id: "banner_04",
    isBanner: true,
    colSpan: 3,
    image: {
      src: "./images/banner_row_1_col_3.png",
      width: 1124,
      height: 534,
    },
  },

  {
    id: "product_28",
    thumbnail: "./images/thumbnail_28.jpg",
    hearted: false,
    title: "M'S MOUNTAIN PEAK JACKET",
    price: "249,000원",
    tags: ["아웃도어활동용", "레귤러핏"],
  },
  {
    id: "product_29",
    thumbnail: "./images/thumbnail_29.jpg",
    hearted: false,
    title: "M'S DENALI WIND EX JACKET",
    price: "98,000원",
    discount: "30%",
    originalPrice: "140,000원",
    tags: ["캠핑용", "세미루즈핏", "온라인단독"],
  },
  {
    id: "product_30",
    thumbnail: "./images/thumbnail_30.jpg",
    hearted: false,
    label: "New Arrival",
    title: "M'S GORETEX HIKER JACKET",
    price: "419,000원",
    tags: ["산행용", "레귤러핏"],
  },
  {
    id: "product_31",
    thumbnail: "./images/thumbnail_31.jpg",
    hearted: false,
    title: "RESTON JACKET",
    price: "98,000원",
    discount: "30%",
    originalPrice: "140,000원",
    tags: ["여행용", "루즈핏"],
  },
  {
    id: "product_32",
    thumbnail: "./images/thumbnail_32.jpg",
    hearted: false,
    title: "M'S MOUNTAIN PEAK JACKET",
    price: "199,200원",
    rating: "5.0",
    reviews: "40",
    tags: ["아웃도어활동용", "레귤러핏"],
  },
  {
    id: "product_33",
    thumbnail: "./images/thumbnail_33.jpg",
    hearted: false,
    label: "New Arrival",
    title: "M'S GO MOUNTAIN JACKET",
    price: "179,000원",
    tags: ["산행용", "레귤러핏"],
  },
  {
    id: "product_34",
    thumbnail: "./images/thumbnail_34.jpg",
    hearted: false,
    title: "M SUMMIT SUPERIOR FUTURELIGHT JACKET",
    price: "371,000원",
    discount: "20%",
    originalPrice: "530,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["트레일러닝용"],
  },
  {
    id: "product_35",
    thumbnail: "./images/thumbnail_35.jpg",
    hearted: false,
    title: "M'S MOUNTAIN PEAK JACKET",
    price: "199,200원원",
    tags: ["아웃도어활동용", "레귤러핏"],
  },
  {
    id: "product_36",
    thumbnail: "./images/thumbnail_36.jpg",
    hearted: false,
    label: "New Arrival",
    title: "M'S LEWES T JACKET",
    price: "169,000원",
    tags: ["여행용", "간절기방한용", "레귤러핏"],
  },
  {
    id: "product_37",
    thumbnail: "./images/thumbnail_37.jpg",
    hearted: false,
    title: "HI MOUNTAIN JACKET",
    price: "219,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["캠핑용", "레귤러핏"],
  },
  {
    id: "product_38",
    thumbnail: "./images/thumbnail_38.jpg",
    hearted: false,
    label: "White Label",
    title: "FELIX GORE-TEX JACKET",
    price: "496,000원",
    discount: "20%",
    originalPrice: "620,000원",
    tags: ["전문등산용", "레귤러핏"],
  },
  {
    id: "product_39",
    thumbnail: "./images/thumbnail_39.jpg",
    hearted: false,
    title: "M'S MOUNTAIN PEAK JACKET",
    price: "249,000원",
    tags: ["아웃도어활동용", "레귤러핏"],
  },
  {
    id: "product_40",
    thumbnail: "./images/thumbnail_40.jpg",
    hearted: false,
    label: "New Arrival",
    title: "M'S GO MOUNTAIN JACKET",
    price: "179,000원",
    tags: ["산행용", "레귤러핏"],
  },
  {
    id: "product_41",
    thumbnail: "./images/thumbnail_41.jpg",
    hearted: false,
    title: "M'S MOUNTAIN PEAK JACKET",
    price: "249,000원",
    discount: "20%",
    originalPrice: "170,000원",
    rating: "5.0",
    reviews: "40",
    tags: ["아웃도어활동용", "레귤러핏"],
  },
  {
    id: "product_42",
    thumbnail: "./images/thumbnail_42.jpg",
    hearted: false,
    title: "HI MOUNTAIN JACKET",
    price: "219,000원",
    tags: ["캠핑용", "루즈핏"],
  },
];
